name: Test

on:
  push: { branches: ["main"] }
  pull_request: { branches: ["main"] }
  repository_dispatch:
  workflow_dispatch:

env:
  REQUIRE_AUTH: false

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:latest
        ports: ["5432:5432"]
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: password
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - name: Cache compiled build
        id: cache-build
        uses: actions/cache@v3
        env:
          cache-name: cache-compiled-build
        with:
          path: _build
          key: ${{ runner.os }}-mix-${{ env.cache-name }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-${{ env.cache-name }}-
            ${{ runner.os }}-mix-
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "25.3"
          elixir-version: "1.14.5"
      - run: mix deps.get
      - run: mix test
